# Generated by Django 4.1.3 on 2022-11-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_useraccount_options_alter_useraccount_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='country',
            field=models.CharField(choices=[('JAPAN', 'JAPAN'), ('france', 'France'), ('germany', 'Germany'), ('china', 'China')], default='', max_length=10),
        ),
    ]
