# Generated by Django 4.1.3 on 2022-11-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_useraccount_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='country',
            field=models.CharField(choices=[('japan', 'Japan'), ('france', 'France'), ('germany', 'Germany'), ('china', 'China')], default='', max_length=10),
        ),
    ]
