# Generated by Django 4.1.3 on 2022-11-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BomAssemblyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent_Item_No', models.CharField(default='', max_length=20)),
                ('No', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=25)),
                ('AssemblyBOM', models.CharField(default='', max_length=25)),
                ('Quantity_per', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='BomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent_Item_No', models.CharField(default='', max_length=20)),
                ('No', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=25)),
                ('AssemblyBOM', models.CharField(default='', max_length=25)),
                ('Quantity_per', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.CharField(default='', max_length=20)),
                ('Description', models.CharField(default='', max_length=50)),
                ('Box_No', models.CharField(default='', max_length=25)),
                ('AssemblyBOM', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
