# Generated by Django 4.1.3 on 2022-11-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordermsbc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BomTable',
        ),
    ]
