# Generated by Django 4.1.3 on 2022-12-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermsbc', '0006_itemcard_net_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='C_num',
            field=models.CharField(default='', max_length=25),
        ),
    ]
