# Generated by Django 4.1.3 on 2022-11-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='base_item_code',
            field=models.CharField(default='', max_length=25),
        ),
    ]
