# Generated by Django 4.1.3 on 2022-11-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_base_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consignee',
            field=models.CharField(default='', max_length=50),
        ),
    ]
