# Generated by Django 4.1.3 on 2022-11-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_consignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='base_item_code',
            field=models.IntegerField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='itemcode',
            field=models.IntegerField(default='', max_length=25),
        ),
    ]
