# Generated by Django 4.1.3 on 2022-11-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_base_item_code_alter_order_itemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='base_item_code',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='itemcode',
            field=models.CharField(default='', max_length=25),
        ),
    ]
