# Generated by Django 4.1.3 on 2022-11-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_base_item_code_alter_order_itemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
