# Generated by Django 4.1.3 on 2022-11-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
    ]
