# Generated by Django 4.1.3 on 2022-11-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='number',
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
